service: serverless-calc
useDotenv: true

provider:
  name: aws
  stage: development
  region: us-west-1
  runtime: nodejs12.x
  apiGateway:
    shouldStartNameWithService: true

custom:
  serverless-offline-sqs:
    autoCreate: true # create queue if not exists
    apiVersion: "2012-11-05"
    endpoint: http://localhost:9324
    region: us-west-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false

plugins:
  - serverless-plugin-typescript
  - serverless-offline-sqs
  - serverless-offline

functions:
  commands:
    handler: src/ports/slack.commandHandler
    events:
      - http:
          path: /slack/{command}
          method: post
  add:
    handler: src/ports/calculator.add
    reservedConcurrency: 10 #Concurrency control
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyCalcCommandsQueue
              - Arn
      - http:
          path: /add
          method: post

  divide:
    handler: src/ports/calculator.divide
    events:
      - http:
          path: /divide
          method: post

resources:
  Resources:
    MyCalcCommandsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: MyCalcCommandsQueue
